// -- THIS FILE IS AUTOGENERATED - DO NOT EDIT!!! ---

import CImGuizmo

// swiftlint:disable identifier_name

// Undeclared type definitions
public typealias ImChunkStream = OpaquePointer
public typealias ImPool = OpaquePointer

